import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import styles from "./rootStyle.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <head />
      <body>
<header data-theme="light" >

  <nav className="mx-auto px-6 text-white bg-black font-bold">

    <div className="container justify-content-center">
        <div className="navbar-header">
            <a href="/" className="navbar-brand">@S-tech</a>
</div>
        <div className="navbar-collapse collapse">
            <ul className="nav navbar-nav ">
            <li className="nav-item">
                    <a className="nav-link" href="login">Log In</a>
                </li>
                <li className="nav-item">
                    <a className="nav-link" href="about">About</a>
                </li>            
            </ul>
            <div className="justify-right">
              <li>
                    <form className="d-flex form-inline md-2 justify-right" role="search">
                        <input className="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                        <button className="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </li>
                </div>
        </div>
    </div>
</nav>
</header> 

<main>
        <h2>    
          <div className={styles.menuBarLink}>{children}</div>
</h2>
   
   </main>
</body>
    </html>
  );
}


